// config.js
// REMPLACEZ CES VALEURS PAR CELLES DE VOTRE PROJET SUPABASE
const CONFIG = {
    SUPABASE_URL: 'https://ahofuucxidbidtxsinid.supabase.co',
    SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFob2Z1dWN4aWRiaWR0eHNpbmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMzQzNTUsImV4cCI6MjA5MjgxMDM1NX0.Pdj6zMNT__CWndCjPFSPI8mJVqiwRlVyN5xBZB26T8U'
};
